SHELL := /bin/bash

.PHONY: serve build new-post compress-image compress-all clean help

# Default target
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

serve: ## Start local dev server with drafts enabled
	hugo server -D

build: ## Build site with production settings
	hugo --gc --minify

new-post: ## Create a new post (usage: make new-post name=my-post-slug)
	@if [ -z "$(name)" ]; then echo "Usage: make new-post name=my-post-slug"; exit 1; fi
	hugo new posts/$(name).md
	@echo "Created content/posts/$(name).md"

compress-image: ## Compress a single image to WebP (usage: make compress-image src=path/to/image.png)
	@if [ -z "$(src)" ]; then echo "Usage: make compress-image src=path/to/image.png"; exit 1; fi
	@command -v cwebp >/dev/null 2>&1 || { echo "cwebp not found. Install with: brew install webp"; exit 1; }
	cwebp -q 80 "$(src)" -o "$$(echo "$(src)" | sed 's/\.[^.]*$$/.webp/')"

compress-all: ## Compress all PNG/JPG images in static/images/ to WebP
	@command -v cwebp >/dev/null 2>&1 || { echo "cwebp not found. Install with: brew install webp"; exit 1; }
	@shopt -s nullglob; for f in static/images/*.png static/images/*.jpg static/images/*.jpeg; do \
		out="$${f%.*}.webp"; \
		echo "Converting $$f -> $$out"; \
		cwebp -q 80 "$$f" -o "$$out"; \
	done

clean: ## Remove generated files
	rm -rf public/ resources/

blossom-words: ## Regenerate static/js/blossom-words.js from curated bank + dwyl/english-words
	@command -v python3 >/dev/null 2>&1 || { echo "python3 required"; exit 1; }
	@if [ ! -f /tmp/blossom-words-alpha.txt ]; then \
		echo "Downloading words_alpha.txt..."; \
		curl -fsSL https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt | tr -d '\r' > /tmp/blossom-words-alpha.txt; \
	fi
	@python3 -c "$$BLOSSOM_WORDS_PY"
	@echo "Wrote static/js/blossom-words.js ($$(wc -c < static/js/blossom-words.js | tr -d ' ') bytes)"

define BLOSSOM_WORDS_PY
import json
with open('assets/blossom/word_bank.txt') as f:
    bank = sorted({w.strip().lower() for w in f if w.strip() and w.strip().isalpha()})
with open('/tmp/blossom-words-alpha.txt') as f:
    broad = {w.strip().lower() for w in f if w.strip() and 3 <= len(w.strip()) <= 7 and w.strip().isalpha()}
valid = sorted(broad | set(bank))
with open('static/js/blossom-words.js', 'w') as f:
    f.write('// AUTO-GENERATED by `make blossom-words` — do not edit by hand.\n')
    f.write('// Source: assets/blossom/word_bank.txt (curated) + dwyl/english-words (3-7 letter).\n')
    f.write('//   BLOSSOM_WORDS     = validation pool (broad).\n')
    f.write('//   BLOSSOM_GEN_WORDS = generation pool (= curated word_bank.txt).\n')
    f.write('window.BLOSSOM_WORDS = ' + json.dumps('\n'.join(valid)) + '.split("\\n");\n')
    f.write('window.BLOSSOM_GEN_WORDS = ' + json.dumps('\n'.join(bank)) + '.split("\\n");\n')
endef
export BLOSSOM_WORDS_PY
